// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use MIGRATE_DATABASE_URL (direct connection) for migrations to avoid
    // advisory-lock timeouts on pooled providers like Neon. Fall back to the
    // regular DATABASE_URL used by the application.
    url: process.env["MIGRATE_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
